name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:

    runs-on:
      - self-hosted
      - macOS

    steps:

      - name: Show Host
        run: hostname

      - name: Show Current Directory
        run: pwd

      - name: Java Version
        run: java -version

      - name: Docker Version
        run: docker --version

      - name: Kubectl Version
        run: kubectl version --client

      - name: Helm Version
        run: helm version

      - name: Minikube Status
        run: minikube status